### ISSUE TITLE
New update script doesn't work due to branch protections

### ISSUE THREAD

**Issue by rkalis** [taylorjdawson/eth-chains#16]
Hey @taylorjdawson! Thanks for merging my earlier PR. It looks like the runs fail due to branch protection on the `main` branch, so either we'll need to loosen the branch protection, or otherwise add an approval process (probably by splitting up the action into (1) creating an "update" PR and (2) releasing after merge into `main`). Let me know if there's anything I can do to help.

**Comment by taylorjdawson** [comment]
@rkalis Yea I took a look and it seems fairly simple to go the route you suggested and just have the action open a pr and merge it in. I can add it sometime this week but if you get to it earlier feel free to open a PR 🤘

**Comment by taylorjdawson** [comment]
Adding something like this I suppose:
```
- name: Commit changes and create PR
  uses: peter-evans/create-pull-request@v3
  with:
    token: ${{ secrets.GH_PAT }}
    branch: "my-feature-branch"
    commit-message: "Update via GitHub Action"
    title: "Update via GitHub Action"
    body: "This PR updates the repository with changes made by the GitHub Action."
    labels: "automated-pr"
```
